-- =====================================================
-- MIGRAÇÃO DE MANUTENÇÃO
-- Data: 2025-12-29
-- Autor: Luis Augusto
-- =====================================================

-- *****************************************************************************************
-- ************** É OBRIGATÓRIO INCLUIR O REGISTRO NA TABELA VERSAO_BASE_DADO **************
-- *****************************************************************************************

INSERT INTO VERSAO_BASE_DADO (VRBD_DATA, VRBD_VERSAO_BASE_DADO, VRBD_DESCRICAO) VALUES
(
    datetime('2025-12-29'),
    'V0018',
    'Alíquotas fixas ligadas a classificações tributárias'
);

-- -----------------------------------------------------------------------------------------------
-- Descrição:
-- 1 - Alíquotas fixas vinculadas a classificações tributárias específicas.
-- 2 - Ajustes nos tratamentos tributários para refletir o uso de alíquotas fixas.
-- -----------------------------------------------------------------------------------------------

INSERT INTO ALIQUOTA_AD_VALOREM(AADV_ID,AADV_VALOR,AADV_TBTO_ID,AADV_INICIO_VIGENCIA,AADV_FIM_VIGENCIA,AADV_CLTR_ID) VALUES(51,1.872,2,'2026-01-01','2033-12-31',64);
INSERT INTO ALIQUOTA_AD_VALOREM(AADV_ID,AADV_VALOR,AADV_TBTO_ID,AADV_INICIO_VIGENCIA,AADV_FIM_VIGENCIA,AADV_CLTR_ID) VALUES(52,0.208,3,'2026-01-01','2033-12-31',64);
INSERT INTO ALIQUOTA_AD_VALOREM(AADV_ID,AADV_VALOR,AADV_TBTO_ID,AADV_INICIO_VIGENCIA,AADV_FIM_VIGENCIA,AADV_CLTR_ID) VALUES(53,0.0,4,'2026-01-01','2033-12-31',64);
INSERT INTO ALIQUOTA_AD_VALOREM(AADV_ID,AADV_VALOR,AADV_TBTO_ID,AADV_INICIO_VIGENCIA,AADV_FIM_VIGENCIA,AADV_CLTR_ID) VALUES(54,0.477,2,'2026-01-01','2033-12-31',65);
INSERT INTO ALIQUOTA_AD_VALOREM(AADV_ID,AADV_VALOR,AADV_TBTO_ID,AADV_INICIO_VIGENCIA,AADV_FIM_VIGENCIA,AADV_CLTR_ID) VALUES(55,0.053,3,'2026-01-01','2033-12-31',65);
INSERT INTO ALIQUOTA_AD_VALOREM(AADV_ID,AADV_VALOR,AADV_TBTO_ID,AADV_INICIO_VIGENCIA,AADV_FIM_VIGENCIA,AADV_CLTR_ID) VALUES(56,0.0,4,'2026-01-01','2033-12-31',65);
INSERT INTO ALIQUOTA_AD_VALOREM(AADV_ID,AADV_VALOR,AADV_TBTO_ID,AADV_INICIO_VIGENCIA,AADV_FIM_VIGENCIA,AADV_CLTR_ID) VALUES(57,3.285,2,'2026-01-01','2033-12-31',66);
INSERT INTO ALIQUOTA_AD_VALOREM(AADV_ID,AADV_VALOR,AADV_TBTO_ID,AADV_INICIO_VIGENCIA,AADV_FIM_VIGENCIA,AADV_CLTR_ID) VALUES(58,0.365,3,'2026-01-01','2033-12-31',66);
INSERT INTO ALIQUOTA_AD_VALOREM(AADV_ID,AADV_VALOR,AADV_TBTO_ID,AADV_INICIO_VIGENCIA,AADV_FIM_VIGENCIA,AADV_CLTR_ID) VALUES(59,0.0,4,'2026-01-01','2033-12-31',66);
INSERT INTO ALIQUOTA_AD_VALOREM(AADV_ID,AADV_VALOR,AADV_TBTO_ID,AADV_INICIO_VIGENCIA,AADV_FIM_VIGENCIA,AADV_CLTR_ID) VALUES(60,3.285,2,'2026-01-01','2033-12-31',67);
INSERT INTO ALIQUOTA_AD_VALOREM(AADV_ID,AADV_VALOR,AADV_TBTO_ID,AADV_INICIO_VIGENCIA,AADV_FIM_VIGENCIA,AADV_CLTR_ID) VALUES(61,0.365,3,'2026-01-01','2033-12-31',67);
INSERT INTO ALIQUOTA_AD_VALOREM(AADV_ID,AADV_VALOR,AADV_TBTO_ID,AADV_INICIO_VIGENCIA,AADV_FIM_VIGENCIA,AADV_CLTR_ID) VALUES(62,0.0,4,'2026-01-01','2033-12-31',67);

UPDATE TRATAMENTO_TRIBUTARIO SET TRTR_DESCRICAO='Alíquota fixa', TRTR_EXPRESSAO_ALIQUOTA='aliquota' WHERE TRTR_ID=34;
UPDATE TRATAMENTO_TRIBUTARIO SET TRTR_DESCRICAO='Alíquota fixa', TRTR_EXPRESSAO_ALIQUOTA='aliquota' WHERE TRTR_ID=35;
UPDATE TRATAMENTO_TRIBUTARIO SET TRTR_DESCRICAO='Alíquota fixa', TRTR_EXPRESSAO_ALIQUOTA='aliquota' WHERE TRTR_ID=36;
UPDATE TRATAMENTO_TRIBUTARIO SET TRTR_DESCRICAO='Alíquota fixa proporcional', TRTR_EXPRESSAO_ALIQUOTA='aliquota' WHERE TRTR_ID=37;

