-- =====================================================
-- MIGRAÇÃO DE MANUTENÇÃO
-- Data: 2025-09-25
-- Autor: Luciano Chaves Neto
-- =====================================================

-- *****************************************************************************************
-- ************** É OBRIGATÓRIO INCLUIR O REGISTRO NA TABELA VERSAO_BASE_DADO **************
-- *****************************************************************************************

INSERT INTO VERSAO_BASE_DADO (VRBD_DATA, VRBD_VERSAO_BASE_DADO, VRBD_DESCRICAO) VALUES
(
    datetime('now'),
    'v0010',
    'Criação da tabela DFE e TIPO_DFE_CLASSIFICACAO, carga de dados e ligação com CLASSIFICACAO_TRIBUTARIA.'
);

-- -----------------------------------------------------------------------------------------------
-- Descrição:
-- 1 - Criação da tabela TIPO_DFE;
-- 2 - Carga de dados da tabela TIPO_DFE;
-- 3 - Criação da tabela associativa TIPO_DFE_CLASSIFICACAO;
-- 4 - Carga de dados da tabela TIPO_DFE_CLASSIFICACAO;
-- 5 - Ligação da tabela TIPO_DFE_CLASSIFICACAO com CLASSIFICACAO_TRIBUTARIA;
-- 6 - Ligação da tabela TIPO_DFE_CLASSIFICACAO com TIPO_DFE.
-- -----------------------------------------------------------------------------------------------

-- -----------------------------------------------------------------------------------------------
-- Início da migração
-- -----------------------------------------------------------------------------------------------

-- -----------------------------------------------------------------------------------------------
-- Criação da tabela TIPO_DFE
-- -----------------------------------------------------------------------------------------------

CREATE TABLE TIPO_DFE
(TPDF_ID INTEGER NOT NULL,
TPDF_TIPO INTEGER,
TPDF_SIGLA TEXT NOT NULL,
TPDF_DESCRICAO TEXT NOT NULL,
TPDF_INICIO_VIGENCIA TEXT NOT NULL,
TPDF_FIM_VIGENCIA TEXT DEFAULT NULL CHECK ("TPDF_FIM_VIGENCIA" IS NULL OR "TPDF_FIM_VIGENCIA" >= "TPDF_INICIO_VIGENCIA"),
PRIMARY KEY (TPDF_ID));

-----------------------------------------------------------------------------------------
-- Carga de dados da tabela TIPO_DFE
-----------------------------------------------------------------------------------------

INSERT INTO TIPO_DFE (TPDF_ID, TPDF_TIPO, TPDF_SIGLA, TPDF_DESCRICAO, TPDF_INICIO_VIGENCIA, TPDF_FIM_VIGENCIA) VALUES
(1, NULL, 'NFe ABI', 'Nota Fiscal Eletrônica da Associação Brasileira da Indústria', '2026-01-01', NULL);

 INSERT INTO TIPO_DFE (TPDF_ID, TPDF_TIPO, TPDF_SIGLA, TPDF_DESCRICAO, TPDF_INICIO_VIGENCIA, TPDF_FIM_VIGENCIA) VALUES
(2, 55, 'NFe', 'Nota Fiscal Eletrônica', '2026-01-01', NULL);

 INSERT INTO TIPO_DFE (TPDF_ID, TPDF_TIPO, TPDF_SIGLA, TPDF_DESCRICAO, TPDF_INICIO_VIGENCIA, TPDF_FIM_VIGENCIA) VALUES
(3, 65, 'NFCe', 'Nota Fiscal de Consumidor Eletrônica', '2026-01-01', NULL);

 INSERT INTO TIPO_DFE (TPDF_ID, TPDF_TIPO, TPDF_SIGLA, TPDF_DESCRICAO, TPDF_INICIO_VIGENCIA, TPDF_FIM_VIGENCIA) VALUES
(4, 57, 'CTe', 'Conhecimento de Transporte Eletrônico', '2026-01-01', NULL);

 INSERT INTO TIPO_DFE (TPDF_ID, TPDF_TIPO, TPDF_SIGLA, TPDF_DESCRICAO, TPDF_INICIO_VIGENCIA, TPDF_FIM_VIGENCIA) VALUES
(5, 67, 'CTe OS', 'Conhecimento de Transporte Eletrônico para Outros Serviços ', '2026-01-01', NULL);

 INSERT INTO TIPO_DFE (TPDF_ID, TPDF_TIPO, TPDF_SIGLA, TPDF_DESCRICAO, TPDF_INICIO_VIGENCIA, TPDF_FIM_VIGENCIA) VALUES
(6, 63, 'BPe', 'Bilhete de Passagem Eletrônico', '2026-01-01', NULL);

 INSERT INTO TIPO_DFE (TPDF_ID, TPDF_TIPO, TPDF_SIGLA, TPDF_DESCRICAO, TPDF_INICIO_VIGENCIA, TPDF_FIM_VIGENCIA) VALUES
(7, NULL, 'BPe TA', 'Bilhete de Passagem Eletrônico para Transporte Aéreo', '2026-01-01', NULL);

 INSERT INTO TIPO_DFE (TPDF_ID, TPDF_TIPO, TPDF_SIGLA, TPDF_DESCRICAO, TPDF_INICIO_VIGENCIA, TPDF_FIM_VIGENCIA) VALUES
(8, 93, 'BPe TM', 'Bilhete de Passagem eletrônico de Transporte Metropolitano', '2026-01-01', NULL);

 INSERT INTO TIPO_DFE (TPDF_ID, TPDF_TIPO, TPDF_SIGLA, TPDF_DESCRICAO, TPDF_INICIO_VIGENCIA, TPDF_FIM_VIGENCIA) VALUES
(9, 66, 'NF3e', 'Nota Fiscal de Energia Elétrica Eletrônica', '2026-01-01', NULL);

 INSERT INTO TIPO_DFE (TPDF_ID, TPDF_TIPO, TPDF_SIGLA, TPDF_DESCRICAO, TPDF_INICIO_VIGENCIA, TPDF_FIM_VIGENCIA) VALUES
(10, 91, 'NFSe', 'Nota Fiscal de Serviços Eletrônica', '2026-01-01', NULL);

 INSERT INTO TIPO_DFE (TPDF_ID, TPDF_TIPO, TPDF_SIGLA, TPDF_DESCRICAO, TPDF_INICIO_VIGENCIA, TPDF_FIM_VIGENCIA) VALUES
(11, 92, 'NFSe Via', 'Nota Fiscal de Serviços Eletrônica de Via de Pedágio', '2026-01-01', NULL);

 INSERT INTO TIPO_DFE (TPDF_ID, TPDF_TIPO, TPDF_SIGLA, TPDF_DESCRICAO, TPDF_INICIO_VIGENCIA, TPDF_FIM_VIGENCIA) VALUES
(12, 62, 'NFCom', 'Nota Fiscal Fatura de Serviços de Comunicação Eletrônica', '2026-01-01', NULL);

 INSERT INTO TIPO_DFE (TPDF_ID, TPDF_TIPO, TPDF_SIGLA, TPDF_DESCRICAO, TPDF_INICIO_VIGENCIA, TPDF_FIM_VIGENCIA) VALUES
(13, 94, 'DERE', 'Declaração Eletrônica de Regimes Específicos', '2026-01-01', NULL);

-- -----------------------------------------------------------------------------------------------
-- Criação da tabela TIPO_DFE_CLASSIFICACAO
-- -----------------------------------------------------------------------------------------------

CREATE TABLE TIPO_DFE_CLASSIFICACAO
(TDCL_ID INTEGER NOT NULL,
TDCL_CLTR_ID INTEGER NOT NULL,
TDCL_TPDF_ID INTEGER NOT NULL,
TDCL_INICIO_VIGENCIA TEXT NOT NULL,
TDCL_FIM_VIGENCIA TEXT DEFAULT NULL CHECK ("TDCL_FIM_VIGENCIA" IS NULL OR "TDCL_FIM_VIGENCIA" >= "TDCL_INICIO_VIGENCIA"),
FOREIGN KEY (TDCL_CLTR_ID) REFERENCES CLASSIFICACAO_TRIBUTARIA(CLTR_ID),
FOREIGN KEY (TDCL_TPDF_ID) REFERENCES TIPO_DFE (TPDF_ID),
PRIMARY KEY (TDCL_ID));

-----------------------------------------------------------------------------------------
-- Carga de dados da tabela TIPO_DFE_CLASSIFICACAO
-----------------------------------------------------------------------------------------

INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (1,1,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (2,1,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (3,1,4,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (4,1,5,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (5,1,6,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (6,1,7,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (7,1,8,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (8,1,9,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (9,1,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (10,1,12,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (11,2,11,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (12,3,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (13,4,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (14,5,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (15,5,13,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (16,6,13,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (17,7,13,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (18,8,13,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (19,9,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (20,10,13,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (21,11,13,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (22,12,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (23,12,4,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (24,12,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (25,13,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (26,13,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (27,14,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (28,14,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (29,15,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (30,15,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (31,15,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (32,16,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (33,16,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (34,17,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (35,17,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (36,17,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (37,18,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (38,18,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (39,18,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (40,19,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (41,19,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (42,20,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (43,20,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (44,21,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (45,21,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (46,22,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (47,23,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (48,23,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (49,24,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (50,24,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (51,25,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (52,25,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (53,26,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (54,26,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (55,27,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (56,28,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (57,28,13,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (58,29,13,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (59,30,13,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (60,31,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (61,31,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (62,31,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (63,32,8,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (64,32,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (65,33,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (66,34,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (67,35,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (68,36,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (69,37,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (70,38,1,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (71,38,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (72,39,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (73,40,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (74,41,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (75,41,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (76,41,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (77,42,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (78,42,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (79,42,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (80,43,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (81,43,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (82,44,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (83,44,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (84,45,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (85,45,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (86,46,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (87,46,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (88,47,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (89,47,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (90,48,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (91,49,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (92,49,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (93,49,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (94,50,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (95,50,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (96,51,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (97,52,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (98,53,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (99,54,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (100,54,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (101,55,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (102,55,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (103,55,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (104,56,1,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (105,56,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (106,57,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (107,58,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (108,58,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (109,59,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (110,60,6,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (111,61,4,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (112,61,7,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (113,62,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (114,63,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (115,64,1,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (116,65,1,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (117,66,1,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (118,67,13,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (119,68,1,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (120,68,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (121,69,6,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (122,69,7,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (123,70,6,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (124,70,8,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (125,70,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (126,71,1,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (127,71,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (128,71,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (129,71,4,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (130,71,5,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (131,71,6,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (132,71,7,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (133,71,8,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (134,71,9,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (135,71,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (136,71,12,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (137,72,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (138,73,1,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (139,73,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (140,73,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (141,74,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (142,74,4,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (143,74,5,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (144,74,6,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (145,74,7,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (146,74,9,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (147,74,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (148,74,12,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (149,75,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (150,75,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (151,75,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (152,76,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (153,76,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (154,76,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (155,77,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (156,77,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (157,77,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (158,78,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (159,78,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (160,78,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (161,79,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (162,79,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (163,79,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (164,80,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (165,80,12,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (166,82,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (167,82,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (168,83,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (169,84,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (170,84,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (171,84,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (172,85,4,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (173,85,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (174,86,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (175,87,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (176,88,1,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (177,88,13,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (178,89,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (179,89,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (180,90,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (181,90,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (182,91,9,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (183,97,1,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (184,97,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (185,97,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (186,97,4,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (187,97,5,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (188,97,6,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (189,97,7,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (190,97,8,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (191,97,9,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (192,97,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (193,97,12,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (194,98,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (195,98,9,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (196,99,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (197,99,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (198,100,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (199,101,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (200,102,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (201,103,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (202,104,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (203,105,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (204,106,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (205,107,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (206,108,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (207,109,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (208,110,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (209,111,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (210,112,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (211,113,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (212,114,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (213,115,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (214,115,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (215,116,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (216,117,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (217,118,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (218,119,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (219,120,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (220,120,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (221,121,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (222,121,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (223,122,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (224,122,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (225,123,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (226,123,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (227,124,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (228,124,3,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (229,125,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (230,125,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (231,126,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (232,126,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (233,127,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (234,128,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (235,129,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (236,130,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (237,131,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (238,132,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (239,133,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (240,134,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (241,135,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (242,136,1,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (243,136,13,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (244,137,10,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (245,138,2,'2026-01-01', NULL);
INSERT INTO TIPO_DFE_CLASSIFICACAO (TDCL_ID, TDCL_CLTR_ID, TDCL_TPDF_ID, TDCL_INICIO_VIGENCIA, TDCL_FIM_VIGENCIA) VALUES (246,138,9,'2026-01-01', NULL);

