-- =====================================================
-- MIGRAÇÃO DE MANUTENÇÃO
-- Data: 2025-12-12
-- Autor: Felipe Zschornack
-- =====================================================

-- *****************************************************************************************
-- ************** É OBRIGATÓRIO INCLUIR O REGISTRO NA TABELA VERSAO_BASE_DADO **************
-- *****************************************************************************************

INSERT INTO VERSAO_BASE_DADO (VRBD_DATA, VRBD_VERSAO_BASE_DADO, VRBD_DESCRICAO) VALUES
(
    datetime('2025-12-12'),
    'V0016',
    'Ajuste de colunas sem tipo definido na criação'
);

-- -----------------------------------------------------------------------------------------------
-- Descrição:
-- 1 - Ajusta colunas da tabela CLASSIFICACAO_TRIBUTARIA para definir tipos corretos.
-- 2 - Ajusta colunas da tabela SITUACAO_TRIBUTARIA para definir tipos corretos.
-- -----------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------
-- Tratamento para CLASSIFICACAO_TRIBUTARIA
----------------------------------------------------------------------------------------
-- Adiciona novas colunas com tipo INTEGER, NOT NULL e CHECK constraint
ALTER TABLE CLASSIFICACAO_TRIBUTARIA ADD COLUMN CLTR_IND_GCREDPRESOPER_NEW INTEGER NOT NULL DEFAULT 0 CHECK (CLTR_IND_GCREDPRESOPER_NEW IN (0, 1));
ALTER TABLE CLASSIFICACAO_TRIBUTARIA ADD COLUMN CLTR_IND_GMONOPADRAO_NEW INTEGER NOT NULL DEFAULT 0 CHECK (CLTR_IND_GMONOPADRAO_NEW IN (0, 1));
ALTER TABLE CLASSIFICACAO_TRIBUTARIA ADD COLUMN CLTR_IND_GMONORETEN_NEW INTEGER NOT NULL DEFAULT 0 CHECK (CLTR_IND_GMONORETEN_NEW IN (0, 1));
ALTER TABLE CLASSIFICACAO_TRIBUTARIA ADD COLUMN CLTR_IND_GMONORET_NEW INTEGER NOT NULL DEFAULT 0 CHECK (CLTR_IND_GMONORET_NEW IN (0, 1));
ALTER TABLE CLASSIFICACAO_TRIBUTARIA ADD COLUMN CLTR_IND_GMONODIF_NEW INTEGER NOT NULL DEFAULT 0 CHECK (CLTR_IND_GMONODIF_NEW IN (0, 1));
ALTER TABLE CLASSIFICACAO_TRIBUTARIA ADD COLUMN CLTR_IND_GESTORNOCRED_NEW INTEGER NOT NULL DEFAULT 0 CHECK (CLTR_IND_GESTORNOCRED_NEW IN (0, 1));
ALTER TABLE CLASSIFICACAO_TRIBUTARIA ADD COLUMN CLTR_ANEXO_NEW TEXT;

-- Cria trigger para abortar se houver divergência na CLASSIFICACAO_TRIBUTARIA
CREATE TEMP TRIGGER valida_migracao_classificacao_tributaria
BEFORE UPDATE ON CLASSIFICACAO_TRIBUTARIA
WHEN
    NEW.CLTR_IND_GCREDPRESOPER_NEW    != COALESCE(CAST(OLD.CLTR_IND_GCREDPRESOPER AS INTEGER), 0)
    OR NEW.CLTR_IND_GMONOPADRAO_NEW   != COALESCE(CAST(OLD.CLTR_IND_GMONOPADRAO AS INTEGER), 0)
    OR NEW.CLTR_IND_GMONORETEN_NEW    != COALESCE(CAST(OLD.CLTR_IND_GMONORETEN AS INTEGER), 0)
    OR NEW.CLTR_IND_GMONORET_NEW      != COALESCE(CAST(OLD.CLTR_IND_GMONORET AS INTEGER), 0)
    OR NEW.CLTR_IND_GMONODIF_NEW      != COALESCE(CAST(OLD.CLTR_IND_GMONODIF AS INTEGER), 0)
    OR NEW.CLTR_IND_GESTORNOCRED_NEW  != COALESCE(CAST(OLD.CLTR_IND_GESTORNOCRED AS INTEGER), 0)
    OR NEW.CLTR_ANEXO_NEW             != OLD.CLTR_ANEXO
BEGIN
    SELECT RAISE(ABORT, 'ERRO DE MIGRACAO: divergência de dados na CLASSIFICACAO_TRIBUTARIA');
END;

-- Migra os valores das colunas antigas para as novas, convertendo para inteiro
UPDATE CLASSIFICACAO_TRIBUTARIA SET
    CLTR_IND_GCREDPRESOPER_NEW = COALESCE(CAST(CLTR_IND_GCREDPRESOPER AS INTEGER), 0),
    CLTR_IND_GMONOPADRAO_NEW   = COALESCE(CAST(CLTR_IND_GMONOPADRAO AS INTEGER), 0),
    CLTR_IND_GMONORETEN_NEW    = COALESCE(CAST(CLTR_IND_GMONORETEN AS INTEGER), 0),
    CLTR_IND_GMONORET_NEW      = COALESCE(CAST(CLTR_IND_GMONORET AS INTEGER), 0),
    CLTR_IND_GMONODIF_NEW      = COALESCE(CAST(CLTR_IND_GMONODIF AS INTEGER), 0),
    CLTR_IND_GESTORNOCRED_NEW  = COALESCE(CAST(CLTR_IND_GESTORNOCRED AS INTEGER), 0),
    CLTR_ANEXO_NEW             = CLTR_ANEXO;

-- Remove a trigger após a validação
DROP TRIGGER valida_migracao_classificacao_tributaria;

-- Remove as colunas antigas
ALTER TABLE CLASSIFICACAO_TRIBUTARIA DROP COLUMN CLTR_IND_GCREDPRESOPER;
ALTER TABLE CLASSIFICACAO_TRIBUTARIA DROP COLUMN CLTR_IND_GMONOPADRAO;
ALTER TABLE CLASSIFICACAO_TRIBUTARIA DROP COLUMN CLTR_IND_GMONORETEN;
ALTER TABLE CLASSIFICACAO_TRIBUTARIA DROP COLUMN CLTR_IND_GMONORET;
ALTER TABLE CLASSIFICACAO_TRIBUTARIA DROP COLUMN CLTR_IND_GMONODIF;
ALTER TABLE CLASSIFICACAO_TRIBUTARIA DROP COLUMN CLTR_IND_GESTORNOCRED;
ALTER TABLE CLASSIFICACAO_TRIBUTARIA DROP COLUMN CLTR_ANEXO;

-- Renomeia as colunas novas para os nomes originais
ALTER TABLE CLASSIFICACAO_TRIBUTARIA RENAME COLUMN CLTR_IND_GCREDPRESOPER_NEW TO CLTR_IND_GCREDPRESOPER;
ALTER TABLE CLASSIFICACAO_TRIBUTARIA RENAME COLUMN CLTR_IND_GMONOPADRAO_NEW TO CLTR_IND_GMONOPADRAO;
ALTER TABLE CLASSIFICACAO_TRIBUTARIA RENAME COLUMN CLTR_IND_GMONORETEN_NEW TO CLTR_IND_GMONORETEN;
ALTER TABLE CLASSIFICACAO_TRIBUTARIA RENAME COLUMN CLTR_IND_GMONORET_NEW TO CLTR_IND_GMONORET;
ALTER TABLE CLASSIFICACAO_TRIBUTARIA RENAME COLUMN CLTR_IND_GMONODIF_NEW TO CLTR_IND_GMONODIF;
ALTER TABLE CLASSIFICACAO_TRIBUTARIA RENAME COLUMN CLTR_IND_GESTORNOCRED_NEW TO CLTR_IND_GESTORNOCRED;
ALTER TABLE CLASSIFICACAO_TRIBUTARIA RENAME COLUMN CLTR_ANEXO_NEW TO CLTR_ANEXO;

----------------------------------------------------------------------------------------
-- Tratamento para SITUACAO_TRIBUTARIA
----------------------------------------------------------------------------------------
-- Adiciona novas colunas com tipo INTEGER, NOT NULL e CHECK constraint
ALTER TABLE SITUACAO_TRIBUTARIA ADD COLUMN SITR_IND_GIBSCBS_NEW INTEGER NOT NULL DEFAULT 0 CHECK (SITR_IND_GIBSCBS_NEW IN (0, 1));
ALTER TABLE SITUACAO_TRIBUTARIA ADD COLUMN SITR_IND_GIBSCBSMONO_NEW INTEGER NOT NULL DEFAULT 0 CHECK (SITR_IND_GIBSCBSMONO_NEW IN (0, 1));
ALTER TABLE SITUACAO_TRIBUTARIA ADD COLUMN SITR_IND_GRED_NEW INTEGER NOT NULL DEFAULT 0 CHECK (SITR_IND_GRED_NEW IN (0, 1));
ALTER TABLE SITUACAO_TRIBUTARIA ADD COLUMN SITR_IND_GDIF_NEW INTEGER NOT NULL DEFAULT 0 CHECK (SITR_IND_GDIF_NEW IN (0, 1));
ALTER TABLE SITUACAO_TRIBUTARIA ADD COLUMN SITR_IND_GTRANSFCRED_NEW INTEGER NOT NULL DEFAULT 0 CHECK (SITR_IND_GTRANSFCRED_NEW IN (0, 1));
ALTER TABLE SITUACAO_TRIBUTARIA ADD COLUMN SITR_IND_GCREDPRESIBSZFM_NEW INTEGER NOT NULL DEFAULT 0 CHECK (SITR_IND_GCREDPRESIBSZFM_NEW IN (0, 1));
ALTER TABLE SITUACAO_TRIBUTARIA ADD COLUMN SITR_IND_GAJUSTECOMPET_NEW INTEGER NOT NULL DEFAULT 0 CHECK (SITR_IND_GAJUSTECOMPET_NEW IN (0, 1));

-- Repita para SITUACAO_TRIBUTARIA
CREATE TEMP TRIGGER valida_migracao_situacao_tributaria
BEFORE UPDATE ON SITUACAO_TRIBUTARIA
WHEN
    NEW.SITR_IND_GIBSCBS_NEW            != COALESCE(CAST(OLD.SITR_IND_GIBSCBS AS INTEGER), 0)
    OR NEW.SITR_IND_GIBSCBSMONO_NEW     != COALESCE(CAST(OLD.SITR_IND_GIBSCBSMONO AS INTEGER), 0)
    OR NEW.SITR_IND_GRED_NEW            != COALESCE(CAST(OLD.SITR_IND_GRED AS INTEGER), 0)
    OR NEW.SITR_IND_GDIF_NEW            != COALESCE(CAST(OLD.SITR_IND_GDIF AS INTEGER), 0)
    OR NEW.SITR_IND_GTRANSFCRED_NEW     != COALESCE(CAST(OLD.SITR_IND_GTRANSFCRED AS INTEGER), 0)
    OR NEW.SITR_IND_GCREDPRESIBSZFM_NEW != COALESCE(CAST(OLD.SITR_IND_GCREDPRESIBSZFM AS INTEGER), 0)
    OR NEW.SITR_IND_GAJUSTECOMPET_NEW   != COALESCE(CAST(OLD.SITR_IND_GAJUSTECOMPET AS INTEGER), 0)
BEGIN
    SELECT RAISE(ABORT, 'ERRO DE MIGRACAO: divergência de dados na SITUACAO_TRIBUTARIA');
END;

-- Migra os valores das colunas antigas para as novas, convertendo para inteiro
UPDATE SITUACAO_TRIBUTARIA SET
    SITR_IND_GIBSCBS_NEW         = COALESCE(CAST(SITR_IND_GIBSCBS AS INTEGER), 0),
    SITR_IND_GIBSCBSMONO_NEW     = COALESCE(CAST(SITR_IND_GIBSCBSMONO AS INTEGER), 0),
    SITR_IND_GRED_NEW            = COALESCE(CAST(SITR_IND_GRED AS INTEGER), 0),
    SITR_IND_GDIF_NEW            = COALESCE(CAST(SITR_IND_GDIF AS INTEGER), 0),
    SITR_IND_GTRANSFCRED_NEW     = COALESCE(CAST(SITR_IND_GTRANSFCRED AS INTEGER), 0),
    SITR_IND_GCREDPRESIBSZFM_NEW = COALESCE(CAST(SITR_IND_GCREDPRESIBSZFM AS INTEGER), 0),
    SITR_IND_GAJUSTECOMPET_NEW   = COALESCE(CAST(SITR_IND_GAJUSTECOMPET AS INTEGER), 0);

-- Remove a trigger após a validação
DROP TRIGGER valida_migracao_situacao_tributaria;

-- Remove as colunas antigas
ALTER TABLE SITUACAO_TRIBUTARIA DROP COLUMN SITR_IND_GIBSCBS;
ALTER TABLE SITUACAO_TRIBUTARIA DROP COLUMN SITR_IND_GIBSCBSMONO;
ALTER TABLE SITUACAO_TRIBUTARIA DROP COLUMN SITR_IND_GRED;
ALTER TABLE SITUACAO_TRIBUTARIA DROP COLUMN SITR_IND_GDIF;
ALTER TABLE SITUACAO_TRIBUTARIA DROP COLUMN SITR_IND_GTRANSFCRED;
ALTER TABLE SITUACAO_TRIBUTARIA DROP COLUMN SITR_IND_GCREDPRESIBSZFM;
ALTER TABLE SITUACAO_TRIBUTARIA DROP COLUMN SITR_IND_GAJUSTECOMPET;

-- Renomeia as colunas novas para os nomes originais
ALTER TABLE SITUACAO_TRIBUTARIA RENAME COLUMN SITR_IND_GIBSCBS_NEW TO SITR_IND_GIBSCBS;
ALTER TABLE SITUACAO_TRIBUTARIA RENAME COLUMN SITR_IND_GIBSCBSMONO_NEW TO SITR_IND_GIBSCBSMONO;
ALTER TABLE SITUACAO_TRIBUTARIA RENAME COLUMN SITR_IND_GRED_NEW TO SITR_IND_GRED;
ALTER TABLE SITUACAO_TRIBUTARIA RENAME COLUMN SITR_IND_GDIF_NEW TO SITR_IND_GDIF;
ALTER TABLE SITUACAO_TRIBUTARIA RENAME COLUMN SITR_IND_GTRANSFCRED_NEW TO SITR_IND_GTRANSFCRED;
ALTER TABLE SITUACAO_TRIBUTARIA RENAME COLUMN SITR_IND_GCREDPRESIBSZFM_NEW TO SITR_IND_GCREDPRESIBSZFM;
ALTER TABLE SITUACAO_TRIBUTARIA RENAME COLUMN SITR_IND_GAJUSTECOMPET_NEW TO SITR_IND_GAJUSTECOMPET;
